# Generated by Django 6.0.7 on 2026-07-09 03:00

import django.core.validators
import django.db.models.deletion
import documents.models
import employees.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('RESUME', 'Resume'), ('AADHAAR', 'Aadhaar'), ('PAN', 'PAN'), ('DEGREE_CERTIFICATE', 'Degree Certificate'), ('EXPERIENCE_CERTIFICATE', 'Experience Certificate'), ('OFFER_LETTER', 'Offer Letter')], max_length=30)),
                ('file', models.FileField(upload_to=documents.models.employee_document_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), employees.models.validate_file_size])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employees.employee')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
